Update cron-6am.yaml

diff --git a/.github/workflows/cron-6am.yaml b/.github/workflows/cron-6am.yaml
--- a/.github/workflows/cron-6am.yaml
+++ b/.github/workflows/cron-6am.yaml
@@ -39,15 +39,15 @@ jobs:
       #    if [[ "$?" -gt 0 ]]; then exit 1; else exit 0; fi
       ## shell: bash
 
-      # v2
-      - name: Step 2/2 - Sitemap-Ping - google.com
-        run: |
-          STATUS=$(curl -isSL -o /dev/null -w "%{http_code}" --url 'https://www.google.com/ping?sitemap=https%3A%2F%2Fphoto-of-the-day-unsplash.vercel.app%2Fsitemap.xml')
-          echo ""
-          echo "Status code: $STATUS"
-          echo "Exit code: $?"
-          # exit 1 aborts job with an error; exit 0 means "all good, move on"
-          if [[ STATUS -ne 200 || "$?" -gt 0 ]]; then exit 1; else exit 0; fi
+      # v2 - DEPRECATED
+      #- name: Step 2/2 - Sitemap-Ping - google.com
+      #  run: |
+      #    STATUS=$(curl -isSL -o /dev/null -w "%{http_code}" --url 'https://www.google.com/ping?sitemap=https%3A%2F%2Fphoto-of-the-day-unsplash.vercel.app%2Fsitemap.xml')
+      #    echo ""
+      #    echo "Status code: $STATUS"
+      #    echo "Exit code: $?"
+      #    # exit 1 aborts job with an error; exit 0 means "all good, move on"
+      #    if [[ STATUS -ne 200 || "$?" -gt 0 ]]; then exit 1; else exit 0; fi
 
 
 
